name: Release switchdns

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare binary for upload
        shell: bash
        run: |
          mkdir dist
          cp target/x86_64-unknown-linux-gnu/release/switchdns dist/switchdns-x86_64-unknown-linux-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: switchdns-x86_64-unknown-linux-gnu
          path: dist/switchdns-x86_64-unknown-linux-gnu

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Gather binaries
        run: |
          mkdir upload
          find dist -type f -exec cp {} upload/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
