name: Release switchdns

on:
  push:
    tags:
      - 'v*'  # Matches v0.1.0, v1.0.0, etc.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: switchdns
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: switchdns
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: switchdns.exe
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary for upload
        shell: bash
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/${{ matrix.bin }} dist/switchdns-${{ matrix.target }}${{ matrix.ext }}

      - uses: actions/upload-artifact@v4
        with:
          name: switchdns-${{ matrix.target }}${{ matrix.ext }}
          path: dist/switchdns-${{ matrix.target }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Gather all binaries
        run: |
          mkdir upload
          find dist -type f -exec cp {} upload/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
